services:
  - type: web
    name: makiwa-freight
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DB_USER
        value: makiwa_app_user
      - key: DB_HOST  
        value: dpg-d47l1c2li9vc738qe0lg-a
      - key: DB_DATABASE
        value: makiwa_freight_db_new
      - key: DB_PASSWORD
        value: IfQyZD1bc0X2oHVnQmtU7dHy5xMFBdiz
      - key: DB_PORT
        value: 5432
      - key: DATABASE_URL
        value: postgresql://makiwa_app_user:IfQyZD1bc0X2oHVnQmtU7dHy5xMFBdiz@dpg-d47l1c2li9vc738qe0lg-a/makiwa_freight_db_new
